"""
test_runner_data.py

Test-Daten fuer den KAI Test-Runner.

Enthaelt alle Test-Definitionen als Liste von Tupeln:
(Kategorie, DisplayName, test_file, test_class)
"""

from typing import List, Tuple


def get_all_test_data() -> List[Tuple[str, str, str, str]]:
    """
    Gibt alle Test-Daten zurueck - COMPLETE LIST.

    Returns:
        Liste von Tupeln: (Kategorie, DisplayName, test_file, test_class)
    """
    return [
        # System & Integration
        (
            "System & Integration",
            "SystemSetup",
            "test_system_setup.py",
            "TestSystemSetup",
        ),
        (
            "System & Integration",
            "KaiWorkerIntegration",
            "test_kai_integration.py",
            "TestKaiWorkerIntegration",
        ),
        (
            "System & Integration",
            "EdgeCases",
            "test_kai_integration.py",
            "TestEdgeCases",
        ),
        (
            "System & Integration",
            "DatabaseConsistency",
            "test_kai_integration.py",
            "TestDatabaseConsistency",
        ),
        (
            "System & Integration",
            "LimitsAndPerformance",
            "test_kai_integration.py",
            "TestLimitsAndPerformance",
        ),
        (
            "System & Integration",
            "Entity Extraction Bugfix",
            "test_entity_extraction_bugfix.py",
            "TestEntityExtractionPunctuationBugfix",
        ),
        # KAI Worker
        (
            "KAI Worker",
            "Initialization",
            "test_kai_worker_extended.py",
            "TestKaiWorkerInitialization",
        ),
        (
            "KAI Worker",
            "Command Suggestions",
            "test_kai_worker_extended.py",
            "TestKaiWorkerCommandSuggestions",
        ),
        (
            "KAI Worker",
            "Pattern Recognition",
            "test_kai_worker_extended.py",
            "TestKaiWorkerPatternRecognition",
        ),
        (
            "KAI Worker",
            "Context Handling",
            "test_kai_worker_extended.py",
            "TestKaiWorkerContextHandling",
        ),
        (
            "KAI Worker",
            "Execute Plan",
            "test_kai_worker_extended.py",
            "TestKaiWorkerExecutePlan",
        ),
        (
            "KAI Worker",
            "Helper Methods",
            "test_kai_worker_extended.py",
            "TestKaiWorkerHelperMethods",
        ),
        # Netzwerk (Knowledge Graph)
        (
            "Knowledge Graph",
            "KonzeptNetzwerk Basic",
            "test_netzwerk_basic.py",
            "TestKonzeptNetzwerk",
        ),
        (
            "Knowledge Graph",
            "Core Extended",
            "test_netzwerk_extended.py",
            "TestKonzeptNetzwerkCore",
        ),
        (
            "Knowledge Graph",
            "Patterns Extended",
            "test_netzwerk_extended.py",
            "TestKonzeptNetzwerkPatterns",
        ),
        (
            "Knowledge Graph",
            "Memory Extended",
            "test_netzwerk_extended.py",
            "TestKonzeptNetzwerkMemory",
        ),
        (
            "Knowledge Graph",
            "Word Usage Extended",
            "test_netzwerk_extended.py",
            "TestKonzeptNetzwerkWordUsage",
        ),
        (
            "Knowledge Graph",
            "Feedback Extended",
            "test_netzwerk_extended.py",
            "TestKonzeptNetzwerkFeedback",
        ),
        (
            "Knowledge Graph",
            "Edge Cases",
            "test_netzwerk_extended.py",
            "TestKonzeptNetzwerkEdgeCases",
        ),
        (
            "Knowledge Graph",
            "Error Handling",
            "test_netzwerk_additional.py",
            "TestErrorHandling",
        ),
        (
            "Knowledge Graph",
            "Pattern Prototypes",
            "test_netzwerk_additional.py",
            "TestPatternPrototypes",
        ),
        (
            "Knowledge Graph",
            "Lexical Triggers",
            "test_netzwerk_additional.py",
            "TestLexicalTriggers",
        ),
        (
            "Knowledge Graph",
            "Other Queries",
            "test_netzwerk_additional.py",
            "TestOtherQueries",
        ),
        (
            "Knowledge Graph",
            "Similar Word Finding",
            "test_netzwerk_additional.py",
            "TestSimilarWordFinding",
        ),
        (
            "Knowledge Graph",
            "Episodic Memory",
            "test_netzwerk_additional.py",
            "TestEpisodicMemory",
        ),
        (
            "Knowledge Graph",
            "Inference Episodes",
            "test_netzwerk_additional.py",
            "TestInferenceEpisodes",
        ),
        (
            "Knowledge Graph",
            "Hypothesis Storage",
            "test_netzwerk_additional.py",
            "TestHypothesisStorage",
        ),
        (
            "Knowledge Graph",
            "Query Facts With Synonyms",
            "test_netzwerk_additional.py",
            "TestQueryFactsWithSynonyms",
        ),
        # NLP & Linguistic Processing
        (
            "NLP & Linguistics",
            "MeaningExtractor Basic",
            "test_meaning_extractor_basic.py",
            "TestMeaningExtractor",
        ),
        (
            "NLP & Linguistics",
            "Declarative Statements",
            "test_meaning_extractor_additional.py",
            "TestDeclarativeStatements",
        ),
        (
            "NLP & Linguistics",
            "Question Heuristics",
            "test_meaning_extractor_additional.py",
            "TestQuestionHeuristics",
        ),
        (
            "NLP & Linguistics",
            "Edge Cases",
            "test_meaning_extractor_additional.py",
            "TestEdgeCases",
        ),
        (
            "NLP & Linguistics",
            "Plural Normalization",
            "test_meaning_extractor_additional.py",
            "TestPluralNormalization",
        ),
        (
            "NLP & Linguistics",
            "Explicit Commands",
            "test_meaning_extractor_additional.py",
            "TestExplicitCommands",
        ),
        (
            "NLP & Linguistics",
            "Argument Extraction",
            "test_meaning_extractor_additional.py",
            "TestArgumentExtraction",
        ),
        (
            "NLP & Linguistics",
            "File Commands",
            "test_meaning_extractor_file_commands.py",
            "TestMeaningExtractorFileCommands",
        ),
        (
            "NLP & Linguistics",
            "Linguistik Engine Resource",
            "test_linguistik_engine.py",
            "TestResourceManager",
        ),
        (
            "NLP & Linguistics",
            "Linguistic Preprocessor",
            "test_linguistik_engine.py",
            "TestLinguisticPreprocessor",
        ),
        (
            "NLP & Linguistics",
            "Preprocessor Fallback",
            "test_linguistik_engine.py",
            "TestLinguisticPreprocessorFallback",
        ),
        (
            "NLP & Linguistics",
            "Linguistik Integration",
            "test_linguistik_engine.py",
            "TestIntegration",
        ),
        (
            "NLP & Linguistics",
            "Enhanced NLP",
            "test_enhanced_nlp.py",
            "TestEnhancedNLP",
        ),
        (
            "NLP & Linguistics",
            "Text Normalization Basic",
            "test_text_normalization.py",
            "TestTextNormalizerWithoutSpacy",
        ),
        (
            "NLP & Linguistics",
            "Text Normalization spaCy",
            "test_text_normalization.py",
            "TestTextNormalizerWithSpacy",
        ),
        (
            "NLP & Linguistics",
            "Text Convenience",
            "test_text_normalization.py",
            "TestConvenienceFunctions",
        ),
        (
            "NLP & Linguistics",
            "Text Regression",
            "test_text_normalization.py",
            "TestRegressionSuite",
        ),
        (
            "NLP & Linguistics",
            "Property-Based Normalization",
            "test_property_based_text_normalization.py",
            "test_",
        ),
        # Pattern Matching & Recognition
        (
            "Pattern Recognition",
            "Prototype Basic",
            "test_prototype_matcher_basic.py",
            "TestPrototypingEngine",
        ),
        (
            "Pattern Recognition",
            "Prototype Edge Cases",
            "test_prototype_matcher_additional.py",
            "TestPrototypingEngineEdgeCases",
        ),
        (
            "Pattern Recognition",
            "Prototype Update",
            "test_prototype_matcher_additional.py",
            "TestPrototypeUpdate",
        ),
        (
            "Pattern Recognition",
            "Process Vector",
            "test_prototype_matcher_additional.py",
            "TestProcessVectorScenarios",
        ),
        (
            "Pattern Recognition",
            "Find Best Match",
            "test_prototype_matcher_additional.py",
            "TestFindBestMatchScenarios",
        ),
        (
            "Pattern Recognition",
            "Keyboard Distance",
            "test_pattern_recognition_char.py",
            "TestKeyboardDistance",
        ),
        (
            "Pattern Recognition",
            "Weighted Levenshtein",
            "test_pattern_recognition_char.py",
            "TestWeightedLevenshtein",
        ),
        (
            "Pattern Recognition",
            "Typo Candidate Finder",
            "test_pattern_recognition_char.py",
            "TestTypoCandidateFinder",
        ),
        (
            "Pattern Recognition",
            "Feedback Integration",
            "test_pattern_recognition_char.py",
            "TestFeedbackIntegration",
        ),
        (
            "Pattern Recognition",
            "Sequence Predictor",
            "test_pattern_recognition_sequence.py",
            "TestSequencePredictor",
        ),
        ("Pattern Recognition", "E2E", "test_pattern_recognition_e2e.py", "test_"),
        (
            "Pattern Recognition",
            "Adaptive Thresholds",
            "test_adaptive_pattern_recognition.py",
            "TestAdaptiveThresholds",
        ),
        (
            "Pattern Recognition",
            "Word Frequency",
            "test_adaptive_pattern_recognition.py",
            "TestWordFrequency",
        ),
        (
            "Pattern Recognition",
            "Bayesian Quality",
            "test_adaptive_pattern_recognition.py",
            "TestBayesianPatternQuality",
        ),
        (
            "Pattern Recognition",
            "False Positive Reduction",
            "test_adaptive_pattern_recognition.py",
            "TestFalsePositiveReduction",
        ),
        (
            "Pattern Recognition",
            "Typo Feedback Recording",
            "test_adaptive_pattern_recognition.py",
            "TestTypoFeedbackRecording",
        ),
        (
            "Pattern Recognition",
            "Command Suggestions - Known Typos",
            "test_command_suggestions.py",
            "TestKnownTypoDetection",
        ),
        (
            "Pattern Recognition",
            "Command Suggestions - Fuzzy Matching",
            "test_command_suggestions.py",
            "TestFuzzyMatching",
        ),
        (
            "Pattern Recognition",
            "Command Suggestions - False Positives",
            "test_command_suggestions.py",
            "TestFalsePositivePrevention",
        ),
        (
            "Pattern Recognition",
            "Command Suggestions - Edge Cases",
            "test_command_suggestions.py",
            "TestEdgeCases",
        ),
        (
            "Pattern Recognition",
            "Regex Validator - Valid Patterns",
            "test_regex_validator.py",
            "TestValidPatterns",
        ),
        (
            "Pattern Recognition",
            "Regex Validator - Invalid Patterns",
            "test_regex_validator.py",
            "TestInvalidPatterns",
        ),
        (
            "Pattern Recognition",
            "Regex Validator - Syntax Errors",
            "test_regex_validator.py",
            "TestSyntaxErrors",
        ),
        (
            "Pattern Recognition",
            "Regex Validator - Warnings",
            "test_regex_validator.py",
            "TestWarningDetection",
        ),
        # Learning & Knowledge Acquisition
        ("Learning", "Goal Planner", "test_goal_planner.py", "TestGoalPlanner"),
        (
            "Learning",
            "Interactive Learning",
            "test_interactive_learning.py",
            "TestInteractiveLearning",
        ),
        (
            "Learning",
            "Intelligent Ingestion",
            "test_intelligent_ingestion.py",
            "TestIntelligentIngestion",
        ),
        ("Learning", "Autonomous Learning", "test_autonomous_learning.py", "test_"),
        ("Learning", "Lerne Command", "test_lerne_command.py", "test_"),
        (
            "Learning",
            "Auto Detect Definitions",
            "test_auto_detect_definitions.py",
            "test_",
        ),
        ("Learning", "Auto Detect E2E", "test_auto_detect_e2e.py", "test_"),
        ("Learning", "Definition Strategy", "test_definition_strategy.py", "test_"),
        (
            "Learning",
            "Plural & Definitions",
            "test_plural_and_definitions.py",
            "TestPluralNormalization",
        ),
        (
            "Learning",
            "Definition Storage",
            "test_plural_and_definitions.py",
            "TestDefinitionStorage",
        ),
        (
            "Learning",
            "Integration Scenario",
            "test_plural_and_definitions.py",
            "TestIntegrationScenario",
        ),
        # Reasoning Engines
        (
            "Reasoning",
            "Backward Chaining",
            "test_backward_chaining.py",
            "TestBackwardChaining",
        ),
        (
            "Reasoning",
            "Graph Traversal",
            "test_graph_traversal.py",
            "TestTransitiveRelations",
        ),
        ("Reasoning", "Path Finding", "test_graph_traversal.py", "TestPathFinding"),
        (
            "Reasoning",
            "Multiple Paths",
            "test_graph_traversal.py",
            "TestMultiplePaths",
        ),
        (
            "Reasoning",
            "Inference Explanation",
            "test_graph_traversal.py",
            "TestInferenceExplanation",
        ),
        (
            "Reasoning",
            "Concept Hierarchy",
            "test_graph_traversal.py",
            "TestConceptHierarchy",
        ),
        (
            "Reasoning",
            "Inverse Traversal",
            "test_graph_traversal.py",
            "TestInverseTraversal",
        ),
        (
            "Reasoning",
            "Graph Edge Cases",
            "test_graph_traversal.py",
            "TestEdgeCases",
        ),
        (
            "Reasoning",
            "German Explanations",
            "test_graph_traversal.py",
            "TestGermanExplanations",
        ),
        (
            "Reasoning",
            "Confidence Propagation",
            "test_graph_traversal.py",
            "TestConfidencePropagation",
        ),
        (
            "Reasoning",
            "Abductive Hypothesis",
            "test_abductive_reasoning.py",
            "TestHypothesisGeneration",
        ),
        (
            "Reasoning",
            "Hypothesis Creation",
            "test_abductive_reasoning.py",
            "TestHypothesisCreation",
        ),
        (
            "Reasoning",
            "Template Strategy",
            "test_abductive_reasoning.py",
            "TestTemplateBasedStrategy",
        ),
        (
            "Reasoning",
            "Analogy Strategy",
            "test_abductive_reasoning.py",
            "TestAnalogyBasedStrategy",
        ),
        (
            "Reasoning",
            "Causal Chain",
            "test_abductive_reasoning.py",
            "TestCausalChainStrategy",
        ),
        (
            "Reasoning",
            "Multi Criteria Scoring",
            "test_abductive_reasoning.py",
            "TestMultiCriteriaScoring",
        ),
        (
            "Reasoning",
            "Hypothesis Persistence",
            "test_abductive_reasoning.py",
            "TestHypothesisPersistence",
        ),
        (
            "Reasoning",
            "Abductive Integration",
            "test_abductive_reasoning.py",
            "TestIntegrationWithKaiWorker",
        ),
        (
            "Reasoning",
            "Abductive Edge Cases",
            "test_abductive_reasoning.py",
            "TestEdgeCases",
        ),
        (
            "Reasoning",
            "Abductive Performance",
            "test_abductive_reasoning.py",
            "TestPerformance",
        ),
        (
            "Reasoning",
            "Probabilistic Fact",
            "test_probabilistic_engine.py",
            "TestBeliefState",
        ),
        (
            "Reasoning",
            "Probabilistic Engine",
            "test_probabilistic_engine.py",
            "TestProbabilisticFact",
        ),
        (
            "Reasoning",
            "Probabilistic Engine Core",
            "test_probabilistic_engine.py",
            "TestProbabilisticEngine",
        ),
        (
            "Reasoning",
            "Probabilistic+Logic",
            "test_probabilistic_engine.py",
            "TestIntegrationWithLogicEngine",
        ),
        (
            "Reasoning",
            "Probabilistic Edge Cases",
            "test_probabilistic_engine.py",
            "TestEdgeCases",
        ),
        # Hybrid Reasoning
        (
            "Hybrid Reasoning",
            "Orchestrator",
            "test_hybrid_reasoning.py",
            "TestReasoningOrchestrator",
        ),
        (
            "Hybrid Reasoning",
            "Proof Tree Generation",
            "test_hybrid_reasoning.py",
            "TestHybridProofTreeGeneration",
        ),
        (
            "Hybrid Reasoning",
            "Handler Integration",
            "test_hybrid_reasoning.py",
            "TestInferenceHandlerIntegration",
        ),
        (
            "Hybrid Reasoning",
            "Performance",
            "test_hybrid_reasoning.py",
            "TestPerformance",
        ),
        (
            "Hybrid Reasoning",
            "Edge Cases",
            "test_hybrid_reasoning.py",
            "TestEdgeCases",
        ),
        (
            "Hybrid Reasoning",
            "E2E",
            "test_hybrid_reasoning.py",
            "TestE2EHybridReasoning",
        ),
        (
            "Hybrid Reasoning",
            "Aggregation Methods",
            "test_hybrid_reasoning_phase2.py",
            "TestAggregationMethods",
        ),
        (
            "Hybrid Reasoning",
            "YAML Configuration",
            "test_hybrid_reasoning_phase2.py",
            "TestYAMLConfiguration",
        ),
        (
            "Hybrid Reasoning",
            "Result Caching",
            "test_hybrid_reasoning_phase2.py",
            "TestResultCaching",
        ),
        (
            "Hybrid Reasoning",
            "Parallel Execution",
            "test_hybrid_reasoning_phase2.py",
            "TestParallelExecution",
        ),
        (
            "Hybrid Reasoning",
            "Optimizations",
            "test_hybrid_reasoning_phase2.py",
            "TestPerformanceOptimizations",
        ),
        (
            "Hybrid Reasoning",
            "Strategy Weights",
            "test_hybrid_reasoning_phase2.py",
            "TestStrategyWeights",
        ),
        (
            "Hybrid Reasoning",
            "Phase2 Integration",
            "test_hybrid_reasoning_phase2.py",
            "TestPhase2Integration",
        ),
        # Constraint Reasoning & SAT
        (
            "Constraint & SAT",
            "Constraint Variable",
            "test_constraint_reasoning.py",
            "TestVariable",
        ),
        (
            "Constraint & SAT",
            "Constraint Definition",
            "test_constraint_reasoning.py",
            "TestConstraint",
        ),
        (
            "Constraint & SAT",
            "Constraint Problem",
            "test_constraint_reasoning.py",
            "TestConstraintProblem",
        ),
        (
            "Constraint & SAT",
            "Constraint Solver",
            "test_constraint_reasoning.py",
            "TestConstraintSolver",
        ),
        (
            "Constraint & SAT",
            "N-Queens Problem",
            "test_constraint_reasoning.py",
            "TestNQueensProblem",
        ),
        (
            "Constraint & SAT",
            "Graph Coloring",
            "test_constraint_reasoning.py",
            "TestGraphColoringProblem",
        ),
        (
            "Constraint & SAT",
            "Logic Grid Puzzle",
            "test_constraint_reasoning.py",
            "TestLogicGridPuzzle",
        ),
        (
            "Constraint & SAT",
            "ProofTree Integration",
            "test_constraint_reasoning.py",
            "TestProofTreeIntegration",
        ),
        (
            "Constraint & SAT",
            "Performance Metrics",
            "test_constraint_reasoning.py",
            "TestPerformanceMetrics",
        ),
        (
            "Constraint & SAT",
            "Logic Integration",
            "test_constraint_logic_integration.py",
            "TestConstraintLogicIntegration",
        ),
        (
            "Constraint & SAT",
            "Logic Edge Cases",
            "test_constraint_logic_integration.py",
            "TestConstraintLogicEdgeCases",
        ),
        ("Constraint & SAT", "SAT Literal", "test_sat_solver.py", "TestLiteral"),
        ("Constraint & SAT", "SAT Clause", "test_sat_solver.py", "TestClause"),
        (
            "Constraint & SAT",
            "SAT CNF Formula",
            "test_sat_solver.py",
            "TestCNFFormula",
        ),
        (
            "Constraint & SAT",
            "SAT DPLL Solver",
            "test_sat_solver.py",
            "TestDPLLSolver",
        ),
        ("Constraint & SAT", "SAT Encoder", "test_sat_solver.py", "TestSATEncoder"),
        (
            "Constraint & SAT",
            "Knights and Knaves",
            "test_sat_solver.py",
            "TestKnightsAndKnaves",
        ),
        (
            "Constraint & SAT",
            "Knowledge Base Checker",
            "test_sat_solver.py",
            "TestKnowledgeBaseChecker",
        ),
        (
            "Constraint & SAT",
            "Watched Literals",
            "test_sat_solver.py",
            "TestWatchedLiterals",
        ),
        (
            "Constraint & SAT",
            "Propositional Formula",
            "test_sat_solver.py",
            "TestPropositionalFormula",
        ),
        (
            "Constraint & SAT",
            "CNF Converter",
            "test_sat_solver.py",
            "TestCNFConverter",
        ),
        (
            "Constraint & SAT",
            "SAT Solver Wrapper",
            "test_sat_solver.py",
            "TestSATSolverWrapper",
        ),
        (
            "Constraint & SAT",
            "SAT Convenience",
            "test_sat_solver.py",
            "TestConvenienceFunctions",
        ),
        (
            "Constraint & SAT",
            "SAT Proof Generation",
            "test_sat_solver.py",
            "TestProofGeneration",
        ),
        (
            "Constraint & SAT",
            "SAT Logic Integration",
            "test_sat_solver.py",
            "TestIntegrationWithLogicEngine",
        ),
        (
            "Constraint & SAT",
            "SAT Performance",
            "test_sat_solver.py",
            "TestPerformance",
        ),
        (
            "Constraint & SAT",
            "SAT Consistency",
            "test_sat_consistency.py",
            "TestConsistencyChecking",
        ),
        (
            "Constraint & SAT",
            "SAT Contradiction",
            "test_sat_consistency.py",
            "TestContradictionFinding",
        ),
        (
            "Constraint & SAT",
            "SAT Integration",
            "test_sat_consistency.py",
            "TestIntegrationWithSAT",
        ),
        (
            "Constraint & SAT",
            "SAT Edge Cases",
            "test_sat_consistency.py",
            "TestEdgeCases",
        ),
        (
            "Constraint & SAT",
            "SAT Reasoning Consistency",
            "test_sat_reasoning.py",
            "TestConsistencyChecking",
        ),
        (
            "Constraint & SAT",
            "SAT Contradiction Detection",
            "test_sat_reasoning.py",
            "TestContradictionDetection",
        ),
        (
            "Constraint & SAT",
            "Knights and Knaves Reasoning",
            "test_sat_reasoning.py",
            "TestKnightsAndKnavesSAT",
        ),
        (
            "Constraint & SAT",
            "SAT Generic Capabilities",
            "test_sat_reasoning.py",
            "TestGenericSATCapabilities",
        ),
        (
            "Constraint & SAT",
            "SAT ProofTree",
            "test_sat_reasoning.py",
            "TestProofTreeIntegration",
        ),
        (
            "Constraint & SAT",
            "SAT Reasoning Performance",
            "test_sat_reasoning.py",
            "TestPerformanceAndEdgeCases",
        ),
        (
            "Constraint & SAT",
            "Contradiction Detection",
            "test_contradiction_detection.py",
            "test_",
        ),
        # State-Space Planning
        (
            "State-Space Planning",
            "State Representation",
            "test_state_space_planner.py",
            "TestStateRepresentation",
        ),
        (
            "State-Space Planning",
            "Action Model",
            "test_state_space_planner.py",
            "TestActionModel",
        ),
        (
            "State-Space Planning",
            "Blocks World",
            "test_state_space_planner.py",
            "TestBlocksWorld",
        ),
        (
            "State-Space Planning",
            "Grid Navigation",
            "test_state_space_planner.py",
            "TestGridNavigation",
        ),
        (
            "State-Space Planning",
            "River Crossing",
            "test_state_space_planner.py",
            "TestRiverCrossing",
        ),
        (
            "State-Space Planning",
            "Diagnostic Reasoning",
            "test_state_space_planner.py",
            "TestDiagnosticReasoning",
        ),
        (
            "State-Space Planning",
            "Heuristics",
            "test_state_space_planner.py",
            "TestHeuristics",
        ),
        (
            "State-Space Planning",
            "Temporal Reasoning",
            "test_state_space_planner.py",
            "TestTemporalReasoning",
        ),
        (
            "State-Space Planning",
            "Plan Simulation",
            "test_state_space_planner.py",
            "TestPlanSimulation",
        ),
        (
            "State-Space Planning",
            "Performance",
            "test_state_space_planner.py",
            "TestPerformance",
        ),
        (
            "State-Space Planning",
            "Hybrid Planning",
            "test_state_space_planner.py",
            "TestHybridPlanning",
        ),
        (
            "State-Space Planning",
            "Integration",
            "test_state_space_planner.py",
            "TestIntegration",
        ),
        (
            "State-Space Planning",
            "Blocks World State",
            "test_state_reasoning.py",
            "TestBlocksWorld",
        ),
        (
            "State-Space Planning",
            "Grid Navigation State",
            "test_state_reasoning.py",
            "TestGridNavigation",
        ),
        (
            "State-Space Planning",
            "River Crossing State",
            "test_state_reasoning.py",
            "TestRiverCrossing",
        ),
        (
            "State-Space Planning",
            "State Integration 31",
            "test_state_reasoning.py",
            "TestStateReasoningIntegration31",
        ),
        (
            "State-Space Planning",
            "State Performance 31",
            "test_state_reasoning.py",
            "TestPerformance31",
        ),
        (
            "State-Space Planning",
            "State Object",
            "test_state_reasoning.py",
            "TestState",
        ),
        (
            "State-Space Planning",
            "Action Object",
            "test_state_reasoning.py",
            "TestAction",
        ),
        (
            "State-Space Planning",
            "Planner Object",
            "test_state_reasoning.py",
            "TestStateSpacePlanner",
        ),
        (
            "State-Space Planning",
            "BFS Planning",
            "test_state_reasoning.py",
            "TestBFSPlanning",
        ),
        (
            "State-Space Planning",
            "Utility Functions",
            "test_state_reasoning.py",
            "TestUtilityFunctions",
        ),
        (
            "State-Space Planning",
            "Constraint Integration",
            "test_state_reasoning.py",
            "TestConstraintIntegration",
        ),
        (
            "State-Space Planning",
            "Complex Planning",
            "test_state_reasoning.py",
            "TestComplexPlanning",
        ),
        # Combinatorial Reasoning
        (
            "Combinatorial Reasoning",
            "Permutations & Cycles",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_permutation_creation_and_cycles",
        ),
        (
            "Combinatorial Reasoning",
            "Cycle Distribution",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_cycle_length_distribution",
        ),
        (
            "Combinatorial Reasoning",
            "Max Cycle Length",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_max_cycle_length",
        ),
        (
            "Combinatorial Reasoning",
            "Element Cycle Finder",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_find_element_cycle",
        ),
        (
            "Combinatorial Reasoning",
            "Probability Small",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_probability_max_cycle_exceeds_threshold_small",
        ),
        (
            "Combinatorial Reasoning",
            "Probability Large",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_probability_max_cycle_exceeds_threshold_large",
        ),
        (
            "Combinatorial Reasoning",
            "Expected Cycle Length",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_expected_max_cycle_length",
        ),
        (
            "Combinatorial Reasoning",
            "Random Strategy",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_strategy_random_evaluation",
        ),
        (
            "Combinatorial Reasoning",
            "Cycle Strategy",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_strategy_cycle_following_evaluation",
        ),
        (
            "Combinatorial Reasoning",
            "Strategy Comparison",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_compare_strategies_and_find_optimal",
        ),
        (
            "Combinatorial Reasoning",
            "Permutation Analysis",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_analyze_specific_permutation",
        ),
        (
            "Combinatorial Reasoning",
            "Permutation Composition",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_permutation_composition",
        ),
        (
            "Combinatorial Reasoning",
            "Strategy Parameters",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_strategy_parameter_access",
        ),
        (
            "Combinatorial Reasoning",
            "100 Prisoners Problem",
            "test_combinatorial_reasoning_prisoners.py",
            "TestCombinatorialReasoningPrisoners::test_comprehensive_prisoners_problem_solution",
        ),
        # Memory Systems
        (
            "Memory",
            "Episodic Memory Basic",
            "test_episodic_memory_basic.py",
            "TestEpisodicMemory",
        ),
        (
            "Memory",
            "Inference Episodes",
            "test_episodic_reasoning.py",
            "TestInferenceEpisodeCreation",
        ),
        (
            "Memory",
            "Proof Step Hierarchy",
            "test_episodic_reasoning.py",
            "TestProofStepHierarchy",
        ),
        (
            "Memory",
            "Inference Tracking",
            "test_episodic_reasoning.py",
            "TestInferenceTracking",
        ),
        (
            "Memory",
            "Episodic Edge Cases",
            "test_episodic_reasoning.py",
            "TestEdgeCases",
        ),
        (
            "Memory",
            "Working Memory State",
            "test_working_memory.py",
            "TestReasoningState",
        ),
        ("Memory", "Context Frame", "test_working_memory.py", "TestContextFrame"),
        ("Memory", "Working Memory", "test_working_memory.py", "TestWorkingMemory"),
        ("Memory", "WM Helpers", "test_working_memory.py", "TestHelperFunctions"),
        ("Memory", "WM Complex", "test_working_memory.py", "TestComplexScenarios"),
        (
            "Memory",
            "Deep Nested Contexts",
            "test_working_memory_stress.py",
            "TestDeepNestedContexts",
        ),
        (
            "Memory",
            "Large Reasoning Traces",
            "test_working_memory_stress.py",
            "TestLargeReasoningTraces",
        ),
        (
            "Memory",
            "Memory Leak Prevention",
            "test_working_memory_stress.py",
            "TestMemoryLeakPrevention",
        ),
        (
            "Memory",
            "Multi-Turn Scenarios",
            "test_working_memory_stress.py",
            "TestComplexMultiTurnScenarios",
        ),
        (
            "Memory",
            "Context Summary",
            "test_working_memory_stress.py",
            "TestContextSummaryAndExport",
        ),
        (
            "Memory",
            "Idle Cleanup",
            "test_working_memory_stress.py",
            "TestIdleCleanup",
        ),
        (
            "Memory",
            "Export Import",
            "test_working_memory_stress.py",
            "TestExportImport",
        ),
        (
            "Memory",
            "Word Usage Tracking",
            "test_word_usage_tracking.py",
            "TestTextFragmentation",
        ),
        (
            "Memory",
            "Word Usage Storage",
            "test_word_usage_tracking.py",
            "TestWordUsageStorage",
        ),
        (
            "Memory",
            "Fragment Similarity",
            "test_word_usage_tracking.py",
            "TestFragmentSimilarity",
        ),
        (
            "Memory",
            "Word Usage Integration",
            "test_word_usage_tracking.py",
            "TestWordUsageIntegration",
        ),
        (
            "Memory",
            "Config Integration",
            "test_word_usage_tracking.py",
            "TestConfigIntegration",
        ),
        # Proof & Explanation
        (
            "Proof & Explanation",
            "ProofStep Data",
            "test_proof_explanation.py",
            "TestProofStep",
        ),
        (
            "Proof & Explanation",
            "ProofTreeNode Data",
            "test_proof_explanation.py",
            "TestProofTreeNode",
        ),
        (
            "Proof & Explanation",
            "ProofTree Data",
            "test_proof_explanation.py",
            "TestProofTree",
        ),
        (
            "Proof & Explanation",
            "Explanation Generators",
            "test_proof_explanation.py",
            "TestExplanationGenerators",
        ),
        (
            "Proof & Explanation",
            "NL Generation",
            "test_proof_explanation.py",
            "TestNaturalLanguageGeneration",
        ),
        (
            "Proof & Explanation",
            "Helper Functions",
            "test_proof_explanation.py",
            "TestHelperFunctions",
        ),
        (
            "Proof & Explanation",
            "Integration Functions",
            "test_proof_explanation.py",
            "TestIntegrationFunctions",
        ),
        (
            "Proof & Explanation",
            "Export/Import",
            "test_proof_explanation.py",
            "TestExportImport",
        ),
        (
            "Proof & Explanation",
            "Complex Scenarios",
            "test_proof_explanation.py",
            "TestComplexScenarios",
        ),
        (
            "Proof & Explanation",
            "ProofNodeItem UI",
            "test_proof_tree_widget.py",
            "TestProofNodeItem",
        ),
        (
            "Proof & Explanation",
            "ProofEdgeItem UI",
            "test_proof_tree_widget.py",
            "TestProofEdgeItem",
        ),
        (
            "Proof & Explanation",
            "ProofTreeWidget UI",
            "test_proof_tree_widget.py",
            "TestProofTreeWidget",
        ),
        (
            "Proof & Explanation",
            "Tree Layout",
            "test_proof_tree_widget.py",
            "TestTreeLayoutAlgorithm",
        ),
        (
            "Proof & Explanation",
            "Proof Performance",
            "test_proof_tree_widget.py",
            "TestPerformance",
        ),
        (
            "Proof & Explanation",
            "Proof UI Integration",
            "test_proof_tree_widget.py",
            "TestIntegration",
        ),
        # Dialogue & Context
        (
            "Dialogue",
            "Multi-Turn Dialog",
            "test_dialog_system.py",
            "TestMultiTurnDialogSystem",
        ),
        ("Dialogue", "W-Fragen", "test_w_fragen.py", "TestWFragenVerarbeitung"),
        (
            "Dialogue",
            "All Relation Types",
            "test_all_relation_types.py",
            "TestAllRelationTypes",
        ),
        (
            "Dialogue",
            "Episodic Query Recognition",
            "test_episodic_query_ui.py",
            "TestEpisodicQueryRecognition",
        ),
        (
            "Dialogue",
            "Episodic Query Planning",
            "test_episodic_query_ui.py",
            "TestEpisodicQueryPlanning",
        ),
        (
            "Dialogue",
            "Episodic Response Formatting",
            "test_episodic_query_ui.py",
            "TestEpisodicResponseFormatting",
        ),
        (
            "Dialogue",
            "Episodic Memory Strategy",
            "test_episodic_query_ui.py",
            "TestEpisodicMemoryStrategy",
        ),
        # Document Processing
        (
            "Document Processing",
            "Document Parser",
            "test_document_parser.py",
            "TestDocumentParser",
        ),
        (
            "Document Processing",
            "File Reader Strategy",
            "test_file_reader_strategy.py",
            "TestFileReaderStrategy",
        ),
        (
            "Document Processing",
            "Goal Planner File",
            "test_goal_planner_file_reading.py",
            "TestGoalPlannerFileReading",
        ),
        (
            "Document Processing",
            "File Ingestion E2E",
            "test_file_ingestion_e2e.py",
            "TestFileIngestionE2E",
        ),
        # Confidence & Feedback
        (
            "Confidence",
            "Classification",
            "test_confidence_manager.py",
            "TestConfidenceClassification",
        ),
        (
            "Confidence",
            "Threshold Decisions",
            "test_confidence_manager.py",
            "TestThresholdDecisions",
        ),
        (
            "Confidence",
            "Combination",
            "test_confidence_manager.py",
            "TestConfidenceCombination",
        ),
        (
            "Confidence",
            "Decay",
            "test_confidence_manager.py",
            "TestConfidenceDecay",
        ),
        (
            "Confidence",
            "Specialized Methods",
            "test_confidence_manager.py",
            "TestSpecializedMethods",
        ),
        (
            "Confidence",
            "Metrics",
            "test_confidence_manager.py",
            "TestConfidenceMetrics",
        ),
        (
            "Confidence",
            "UI Feedback",
            "test_confidence_manager.py",
            "TestUIFeedback",
        ),
        (
            "Confidence",
            "Global Instance",
            "test_confidence_manager.py",
            "TestGlobalInstance",
        ),
        ("Confidence", "Edge Cases", "test_confidence_manager.py", "TestEdgeCases"),
        (
            "Confidence",
            "Feedback Collection",
            "test_confidence_feedback.py",
            "TestFeedbackCollection",
        ),
        (
            "Confidence",
            "Adjustment",
            "test_confidence_feedback.py",
            "TestConfidenceAdjustment",
        ),
        (
            "Confidence",
            "Historical Consensus",
            "test_confidence_feedback.py",
            "TestHistoricalConsensus",
        ),
        (
            "Confidence",
            "Persistence",
            "test_confidence_feedback.py",
            "TestFeedbackPersistence",
        ),
        (
            "Confidence",
            "Statistics",
            "test_confidence_feedback.py",
            "TestStatisticsAndReporting",
        ),
        (
            "Confidence",
            "Feedback Global",
            "test_confidence_feedback.py",
            "TestGlobalInstance",
        ),
        (
            "Confidence",
            "Feedback Edge Cases",
            "test_confidence_feedback.py",
            "TestEdgeCases",
        ),
        # Exception Handling
        (
            "Exceptions",
            "KAI Exception Base",
            "test_kai_exceptions.py",
            "TestKAIExceptionBase",
        ),
        (
            "Exceptions",
            "Database Exceptions",
            "test_kai_exceptions.py",
            "TestDatabaseExceptions",
        ),
        (
            "Exceptions",
            "Linguistic Exceptions",
            "test_kai_exceptions.py",
            "TestLinguisticExceptions",
        ),
        (
            "Exceptions",
            "Knowledge Exceptions",
            "test_kai_exceptions.py",
            "TestKnowledgeExceptions",
        ),
        (
            "Exceptions",
            "Reasoning Exceptions",
            "test_kai_exceptions.py",
            "TestReasoningExceptions",
        ),
        (
            "Exceptions",
            "Planning Exceptions",
            "test_kai_exceptions.py",
            "TestPlanningExceptions",
        ),
        (
            "Exceptions",
            "Configuration Exceptions",
            "test_kai_exceptions.py",
            "TestConfigurationExceptions",
        ),
        (
            "Exceptions",
            "Exception Wrapping",
            "test_kai_exceptions.py",
            "TestExceptionWrapping",
        ),
        (
            "Exceptions",
            "Exception Hierarchy",
            "test_kai_exceptions.py",
            "TestExceptionHierarchy",
        ),
        (
            "Exceptions",
            "Exception Catching",
            "test_kai_exceptions.py",
            "TestExceptionCatching",
        ),
        (
            "Exceptions",
            "Exception Handling",
            "test_exception_handling.py",
            "TestKaiExceptionHandling",
        ),
        (
            "Exceptions",
            "Hierarchy Basic",
            "test_exception_handling.py",
            "TestExceptionHierarchy",
        ),
        (
            "Exceptions",
            "Wrap Exception",
            "test_exception_handling.py",
            "TestWrapException",
        ),
        (
            "Exceptions",
            "User Friendly Messages",
            "test_exception_handling.py",
            "TestUserFriendlyMessages",
        ),
        (
            "Exceptions",
            "Exception Inheritance",
            "test_exception_handling.py",
            "TestExceptionInheritance",
        ),
        (
            "Exceptions",
            "Logging System",
            "test_logging_and_exceptions.py",
            "TestLoggingSystem",
        ),
        (
            "Exceptions",
            "Hierarchy Logging",
            "test_logging_and_exceptions.py",
            "TestExceptionHierarchy",
        ),
        (
            "Exceptions",
            "Logging Integration",
            "test_logging_and_exceptions.py",
            "TestIntegrationLoggingAndExceptions",
        ),
        # Performance & Infrastructure
        (
            "Performance",
            "Embedding Service",
            "test_embedding_service.py",
            "TestEmbeddingService",
        ),
        (
            "Performance",
            "Batch Embeddings",
            "test_performance_optimizations.py",
            "TestBatchEmbeddings",
        ),
        (
            "Performance",
            "Batch Processing",
            "test_performance_optimizations.py",
            "TestIngestionBatchProcessing",
        ),
        (
            "Performance",
            "Proof Tree Lazy Loading",
            "test_performance_optimizations.py",
            "TestProofTreeLazyLoading",
        ),
        (
            "Performance",
            "Neo4j Profiler",
            "test_performance_optimizations.py",
            "TestNeo4jQueryProfiler",
        ),
        (
            "Performance",
            "Performance Regression",
            "test_performance_optimizations.py",
            "TestPerformanceRegression",
        ),
        ("Performance", "Cache Performance", "test_cache_performance.py", "test_"),
        (
            "Performance",
            "Error Paths",
            "test_error_paths_and_resilience.py",
            "test_",
        ),
        # Arithmetic & Mathematics
        (
            "Arithmetic & Mathematics",
            "Basic Operations",
            "test_arithmetic_basic_operations.py",
            "test_",
        ),
        (
            "Arithmetic & Mathematics",
            "Comparisons",
            "test_arithmetic_comparisons.py",
            "test_",
        ),
        (
            "Arithmetic & Mathematics",
            "Properties",
            "test_arithmetic_properties.py",
            "test_",
        ),
        (
            "Arithmetic & Mathematics",
            "Concepts",
            "test_arithmetic_concepts.py",
            "test_",
        ),
        (
            "Arithmetic & Mathematics",
            "Fractions & Decimals",
            "test_arithmetic_fractions_decimals.py",
            "test_",
        ),
        (
            "Arithmetic & Mathematics",
            "Advanced Operations",
            "test_arithmetic_advanced.py",
            "test_",
        ),
        (
            "Arithmetic & Mathematics",
            "Number Language",
            "test_number_language.py",
            "test_",
        ),
    ]
